model_params:
  max_depth: 6
  learning_rate: 0.1
  n_estimators: 1000
  subsample: 0.8
  colsample_bytree: 0.8
  reg_alpha: 0.5
  reg_lambda: 1.0
  early_stopping_rounds: 50  # Ensure this exists

validation_size: 0.2
model_version: 1.0